# $Id: Makefile,v 1.1.1.1 2006/08/31 22:40:49 hari Exp $
#
# Various URI checks
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=uri.so
LIBS=

include ../../Makefile.modules

