# $Id: Makefile,v 1.1.1.1 2006/08/31 22:40:56 hari Exp $
#
# database example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=dbexample.so
LIBS=

include ../../Makefile.modules
