# $Id: Makefile,v 1.1.1.1 2006/08/31 22:40:51 hari Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=sl.so
LIBS= 

include ../../Makefile.modules
