# $Id: Makefile,v 1.1.1.1 2006/08/31 22:40:54 hari Exp $
#
#  serunix Makefile
# 

include ../../Makefile.defs

auto_gen=
NAME=serunix
LIBS:=$(filter-out -lfl, $(LIBS) )

include ../../Makefile.sources
include ../../Makefile.rules


modules:
