# $Id: Makefile,v 1.2 2006/12/15 08:10:16 hari Exp $
#
# Usrloc module Makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=usrloc.so
LIBS=

include ../../Makefile.modules
